In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
att=2
n=1000
x=np.random.rand(n,att)
x1=np.ones(n).reshape(n,1)
input_data=np.append(x1,x,axis=1)
beta=np.random.rand(att+1,1)
noise=np.random.randn(n,1)
y_data=np.dot(input_data,beta)
y=y_data+noise
print(input_data.shape)
print(y.shape)
print(noise.shape)
print(beta.shape)

(1000, 3)
(1000, 1)
(1000, 1)
(3, 1)


In [3]:
new_beta=np.random.rand(att+1,1)
new_beta.shape

(3, 1)

In [4]:
for i in range(10000):
    
    y_hat=np.dot(input_data,new_beta)
    y_diff=y-y_hat
    y_eqn=-2*(np.transpose(y_diff))
    der=np.dot(y_eqn,input_data)/n
    #print (der)
    new_beta=(new_beta)-0.1*(der.T)
    y_square=np.square(y_diff)
    cost_value=np.sum(y_square)/n
    #cost_array.append(cost value)
print(cost_value)
print(new_beta)    



#if cost_array[i-1]-cost_array[i]<0.000001:
#    #print(cost_array[i-1],cost_array[i])
#   break
#print(input_data.shape)

0.981149457150276
[[1.03071212]
 [0.01370096]
 [0.89944687]]


In [5]:
# Verify result by using linear regression as implmented in sklearn
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
regr = linear_model.LinearRegression()
input_data = x
# Train the model using the training sets
regr.fit(input_data, y)
# Make predictions using the testing set
y_hat = regr.predict(input_data)
# The coefficients and intercept
print('Coefficients: \n', regr.coef_)
print('Intercept: \n', regr.intercept_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(y, y_hat))

    

Coefficients: 
 [[0.01370096 0.89944687]]
Intercept: 
 [1.03071212]
Mean squared error: 0.98


In [6]:
#OR

In [7]:
from sklearn.linear_model import LinearRegression
regressor= LinearRegression()
regressor.fit(input_data,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [8]:
y_pred=regressor.predict(x)

In [9]:
regressor.coef_

array([[0.01370096, 0.89944687]])

In [10]:
regressor.intercept_

array([1.03071212])

In [11]:
import sklearn
sklearn.metrics.mean_squared_error(y,y_pred)

0.981149457150276